import {
  Activity,
  Banknote,
  Briefcase,
  Building2,
  Car,
  Circle,
  CircleDashed,
  CircleDollarSign,
  Clapperboard,
  Coins,
  CreditCard,
  Dumbbell,
  Fuel,
  Gift,
  HeartPulse,
  Home,
  Landmark,
  MoreHorizontal,
  PiggyBank,
  Plane,
  Receipt,
  RotateCcw,
  ShoppingBag,
  Store,
  TrendingUp,
  Utensils,
  Wallet,
  Wallet2,
  type LucideIcon,
} from 'lucide-react'

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  clapperboard: Clapperboard,
  'heart-pulse': HeartPulse,
  plane: Plane,
  'more-horizontal': MoreHorizontal,
  wallet: Wallet,
  briefcase: Briefcase,
  store: Store,
  'trending-up': TrendingUp,
  gift: Gift,
  'rotate-ccw': RotateCcw,
  'circle-dollar-sign': CircleDollarSign,
  landmark: Landmark,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  banknote: Banknote,
  coins: Coins,
  'building-2': Building2,
  'wallet-2': Wallet2,
  'circle-dashed': CircleDashed,
  fuel: Fuel,
  activity: Activity,
  dumbbell: Dumbbell,
}

export function getIcon(name: string): LucideIcon {
  return ICON_REGISTRY[name] ?? Circle
}

export const ACCOUNT_ICON_OPTIONS = [
  'landmark',
  'wallet',
  'wallet-2',
  'piggy-bank',
  'credit-card',
  'banknote',
  'coins',
  'building-2',
  'trending-up',
  'briefcase',
]

export const ACCOUNT_COLOR_OPTIONS = [
  '#2563eb',
  '#7c3aed',
  '#db2777',
  '#dc2626',
  '#ea580c',
  '#d97706',
  '#65a30d',
  '#059669',
  '#0891b2',
  '#4b5563',
]
